### ISSUE TITLE
DroneInitialize.sh of limited value

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#12]
In this spirit of [this](http://bash.org/?240849), `DroneInitialize.sh` goes to the effort of finding the computer's IP address (`$myIP`), only to discard it and use a constant.

Given #11, does  `DroneInitialize.sh` have any place at all?

**Comment by friether** [comment]
Correct. Currently, the effort of finding the computer's IP address is pointless. However, we plan to keep `DroneInitialize.sh` as part of the process as a placeholder for future potential initialization routines.
