### ISSUE TITLE
Packing and compiling embedded code

### ISSUE THREAD

**Issue by friether** [Parrot-Developers/RollingSpiderEdu#16]
Make this process more robust for different OS, e.g. PackEmbeddedCode currently depends on line endings as pointed out by @eric-wieser

**Comment by eric-wieser** [comment]
I have a python implementation of this on my PC

**Comment by eric-wieser** [comment]
#17

**Comment by friether** [comment]
check https://www.mathworks.com/hardware-support/parrot-minidrones.html
