### ISSUE TITLE
abs(float) returns int in C

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#23]
This might be causing some bugs, since I see it's used a _lot_.

See the docs for [`abs`](http://www.cplusplus.com/reference/cmath/abs/):

> These convenience abs overloads are exclusive of C++. In C, abs is only declared in <stdlib.h> (**and operates on int values**).

**Comment by eric-wieser** [comment]
Is there scope to throw a C++ compiler at this instead?

**Comment by eric-wieser** [comment]
Yep, seems to work fine if I build `rsedu_vis` with a C++ compiler. I think we'd want to split rsedu_control into generated and not to make things easier

**Comment by eric-wieser** [comment]
For the time being though, replacing everything with `fabs` should do the trick

**Comment by friether** [comment]
Good catch.
I think it shouldn't cause considerable problems, but it is definitely better to fix it (might cause jerky motor commands),
I was about to suggest the use of fabs as I am not to sure about possible issues that we could run into when just switching to a c++ compiler.
