### ISSUE TITLE
Sensor calibration seems (negligibly) incorrect

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#28]
In `rsedu_control.c`, This code:

``` c++
    //s1: Record calibration data
    else if(counter < calibCycles)
    {
        sensorCal[0] = sensorCal[0] * (counter - 1) / counter + in->HAL_acc_SI.x / counter;
        sensorCal[1] = sensorCal[1] * (counter - 1) / counter + in->HAL_acc_SI.y / counter;
        sensorCal[2] = sensorCal[2] * (counter - 1) / counter + in->HAL_acc_SI.z / counter;
        sensorCal[3] = sensorCal[3] * (counter - 1) / counter + in->HAL_gyro_SI.x / counter;
        sensorCal[4] = sensorCal[4] * (counter - 1) / counter + in->HAL_gyro_SI.y / counter;
        sensorCal[5] = sensorCal[5] * (counter - 1) / counter + in->HAL_gyro_SI.z / counter;
        sensorCal[6] = sensorCal[6] * (counter - 1) / counter + in->HAL_pressure_SI.pressure / counter;
```

Runs from `counter == 3` to `counter == calibCycles + 1`. This means that the first iteration sets `sensorCal = 1/3 * (reading0 * 2 + reading1);` and the second `sensorCal = 1/4 * (reading0 * 2 + reading1 + reading 2);` - ie, the first reading is double counted.

Presumably this implementation is less prone to floating point error than naive sum-all-then-divide version? If this is a concern, is [Kahan summing](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) favorable?

**Comment by friether** [comment]
thanks, fixed it
