### ISSUE TITLE
Make sim_quadrotor and the drone log output to a common format

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#35]
This would make comparing simulation with reality much easier, and deals with the fact that simulink scopes are terrible for producing document-ready plots.

Obviously making the format output by the C code more complex is probably a bad idea performance-wise, so maybe there could be a pre-processing step to "upgrade" hardware logs into the same format as recorded by the simulation ones.

---

As a quick hack, my working copy currently looks like this:

![image](https://cloud.githubusercontent.com/assets/425260/11619021/afd16a52-9c70-11e5-8d67-5e1a926a8924.png)

So that I can plot the contents of `results` with a script.

**Comment by friether** [comment]
That is an awesome idea!
I augmented the sim_quadrotor.slx and wrote a "data transformation script". Now you can run FlightAnalyzer straight after running a simulation.
