### ISSUE TITLE
Error in quadrotor dynamics

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#37]
I believe this line to be wrong:

```
Vr = cross(o,D(:,i)) + v;
```

o and v are in world space, but D is in body space.

I think this explains the trouble I'm having with my controller in simulation.

**Comment by eric-wieser** [comment]
This seems to come from upstream in petercorke/robotics-toolbox-matlab#13

**Comment by friether** [comment]
o are bodyrates if I am not mistaken, but v should be transformed to the body coordinate system I think.

**Comment by eric-wieser** [comment]
Yep, adding `inv(R)*v` makes the linearization unaffected by initial yaw angle, which was part of the bug I'm tracking down
