### ISSUE TITLE
State estimates diverge from state for x/y position in simulation

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#39]
Estimate on the left, system output on the right

![image](https://cloud.githubusercontent.com/assets/425260/11642535/40e47de0-9d0c-11e5-9133-8b9d305a5863.png)

This is after stepping the yaw angle to pi/2.

I'm working on fixing this for my project

**Comment by eric-wieser** [comment]
This is due to saturation of the position integrator.

This is another blow against simulink for me - it seems to be a very write-only language - I had no way of knowing that the block had a saturation setting without double clicking on it, and had no incentive to do that until bisecting the error to that block.

**Comment by eric-wieser** [comment]
One of these two things is a bug:
- The estimator refuses to estimate a position outside of `[-2 2]^2`
- The c code does a safety abort if the positions leaves `[-10 10]^2`

Clearly the safety check will never run right now

**Comment by friether** [comment]
Thanks for finding this!
I completely removed the saturation now, I couldn't come up with a reason why this makes sense any longer at this stage.
