### ISSUE TITLE
LQRControl implements Bryson's rule incorrectly

### ISSUE THREAD

**Issue by eric-wieser** [Parrot-Developers/RollingSpiderEdu#40]
According to [past lecture notes](http://ocw.mit.edu/courses/aeronautics-and-astronautics/16-30-feedback-control-systems-fall-2010/lecture-notes/MIT16_30F10_lec12.pdf), we should be squaring the maximum values on [these lines](https://github.com/Parrot-Developers/RollingSpiderEdu/blob/master/MIT_MatlabToolbox/trunk/matlab/Simulation/controllers/controller_fullstate/LQR/LQRControl.m#L64-L66)

**Comment by friether** [comment]
Thanks
