### ISSUE TITLE
Error in Embedded Code Generation in Simulink

### ISSUE THREAD

**Issue by whizkidrohan** [Parrot-Developers/RollingSpiderEdu#41]
I am getting the following error while generating C/C++ Code from the Drone_Compensator block in Simulink by clicking on Build This Subsystem:

```
File I/O error on file 'ert_shrlib.tlc'
Operation that caused an error: open
Component: Simulink | Category: Build error
 ??? Subsystem build failed
```

Can't figure out what i'm missing...

**Comment by friether** [comment]
Strange, we never ran into this kind of error.
Could you tell us the MATLAB version you are using and which toolboxes you have installed (in MATLAB, ver)?

**Comment by whizkidrohan** [comment]
I noticed that the embedded coder package was missing. After installing it, I am able to compile successfully without errors. Thank you.
P.S.
Sorry for the delay in the reply, took me a while to get access to the embedded coder package from the university.

**Comment by friether** [comment]
Great, thanks for the feedback!
