### ISSUE TITLE
Using WiFi instead of Bluetooth

### ISSUE THREAD

**Issue by whizkidrohan** [Parrot-Developers/RollingSpiderEdu#43]
I am trying to establish a connection over WiFi instead of Bluetooth to reduce latency. Could you please tell me how to go about this? (Why did you choose to use Bluetooth instead of WiFi?)

**Comment by friether** [comment]
The onboard device for connectivity is a bluetooth (BLE) device, you won't be able to setup a wifi connection. 
My guess is that the bluetooth option was the cheaper one while providing sufficient characteristics for the original purpose of the Rolling Spider.
Hope this helps
