### ISSUE TITLE
Compatibility with other Parrot mini drone

### ISSUE THREAD

**Issue by junpenglao** [Parrot-Developers/RollingSpiderEdu#47]
Thanks for sharing this great material. 

I am trying to follow the set up with my new airborne drone, however, I am stuck on the steps of flashing the firmware of the drone. After I uploaded the rollingspider.edu.plf and waited for the update procedure to complete (LEDs stop blinking), I still cannot connect to the drone system shell. Moreover, I still can connect to the drone using the Parrot app and the firmware of the drone still shown as v.2.1.70

Is there another way to flash the firmware?

**Comment by friether** [comment]
As you correctly hint at, the flashing process does not seem to have succeeded. 
@JeromeBouvard Can we provide more specific compatibility descriptions (i.e. if RollingSpider-versions later than early-2015, or e.g. the airborne cargo, also work)?

**Comment by JeromeBouvard** [comment]
The only compatible drone for this firmware is original ROLLING SPIDER.
Airborne drones are not supported.

**Comment by junpenglao** [comment]
Thanks @friether and @JeromeBouvard , is there any restriction on the version of the ROLLING SPIDER?

**Comment by dionisiodeniz** [comment]
@JeromeBouvard : So, when you say that the firmware is compatible with the original rolling spider, Does it mean an older model that is not available anymore, or the current model that we can still buy?

**Comment by JeromeBouvard** [comment]
There is only one model of Rolling Spider, with the wheels.
Second generation is called Airborne (cargo and night)
Third generation is called Mambo and Swing (just released this week)

This code and firmware was designed for the original Rolling Spider only.
You can NOT flash it on other product.
