### ISSUE TITLE
 WARNING not enough distinct markers (colored balls) found!

### ISSUE THREAD

**Issue by vinhk** [Parrot-Developers/RollingSpiderEdu#48]
How to incorporate the Image processing into the rolling spider?

**Comment by friether** [comment]
The image processing feature is the toolbox' most beta/prototypical feature and will most probably not work out of the box, but can be considered as a starting point for your own coding experiments.
https://github.com/Parrot-Developers/RollingSpiderEdu/blob/master/MIT_MatlabToolbox/media/GettingStarted.pdf pages 23 provides information on what settings should be enabled (depending on your use case). Page 30 illustrates the marker setup that we used. As for the colored dots, we used colored, plastic balls glued to the ground (diameter about 5cm).  However, you will most probably need to update the landmark descriptors (page 29).
