### ISSUE TITLE
Compile error with basic Drone Compensator block

### ISSUE THREAD

**Issue by drjohnpetersen** [Parrot-Developers/RollingSpiderEdu#52]
I am following the "Getting Started" tutorial and haven't modifed any code, just trying to get the basic "Drone Compensator" block to compile.  I can build the code in simulink, and connect to the drone using DroneConnect.sh, but when I run DroneUploadEmbeddedCode.sh shell script that compiles the code there is an error.  I am using Matlab (2016b) on Ubuntu 14.04.  The error is 

../rsedu_control.c: In function 'RSEDU_control':
../rsedu_control.c:1172:23: error: 'RT_MODEL_Drone_Compensator_T' has no member named 'ModelData'

Has anyone seen this error or knows what I might be missing in the simulink files or in the make file?

**Comment by friether** [comment]
I'm pretty sure the issues is caused by using MATLAB 2016>b<.
From 2016a to 2016b, the variable structure of MATLAB-autogenerated code changed.
E.g.` RT_MODEL_Drone_Compensator_T->ModelData.defaultParam` became `RT_MODEL_Drone_Compensator_T->defaultParam`.
It **might** be sufficient to remove the `ModelData.` within trunk/embcode/rsedu_control.c
Chances are there were more changes than this though.

**Comment by drjohnpetersen** [comment]
Thanks!  Do you mean edit the generated c code?  or is there a way to remove "ModelData" from the simulink model?

**Comment by friether** [comment]
"ModelData" is most probably missing in the simulink-autogenerated code itself - but the rest of the c-code that wraps around that autogenerated code assumes it's there.
In trunk/embcode/rsedu_control.c, try replacing
```
	  Drone_Compensator_M->ModelData.defaultParam = &Drone_Compensator_P;
	  Drone_Compensator_M->ModelData.blockIO = &Drone_Compensator_B;
	  Drone_Compensator_M->ModelData.dwork = &Drone_Compensator_DW;
```
with
```
	  Drone_Compensator_M->defaultParam = &Drone_Compensator_P;
	  Drone_Compensator_M->blockIO = &Drone_Compensator_B;
	  Drone_Compensator_M->dwork = &Drone_Compensator_DW;
```
This is off the top of my head, I'd be surprised if that works out of the box. I don't have the chance to try it myself unfortunately.
Hope this helps!

**Comment by drjohnpetersen** [comment]
Worked!  At least it compiled and uploaded the code.  Thank you so much! Now I can move on to the next step!
