### ISSUE TITLE
DroneKeyboardPilot.sh not connecting

### ISSUE THREAD

**Issue by drjohnpetersen** [Parrot-Developers/RollingSpiderEdu#54]
When I run DroneKeyboardPilot.sh, the process says it's waiting for connection, but never connects.  I'm looking for ways to debug this or for someone to identify an error in my process.   I have successfully run DroneUploadEmbeddedCode.sh with the default DroneCompensator simulink code.  The workflow is 
1 - power on
2 - DroneConnect.sh (usually takes 3 times to finally work)
3 - DroneKeyboardPilot.sh  (runs some stuff then hangs on waiting for connection never to return)
Any help would be very ... helpful.

**Comment by drjohnpetersen** [comment]
Okay, if I run DroneTest.sh or DroneRun.sh in a different terminal, the drone runs... but only for a few seconds.  Does any one else have this problem and is there something I can do to get it to run for longer?

**Comment by emiliomarin** [comment]
What does the DroneRun window say about the stop? Usually it says if the drone stopped because of an drone crash, or some other errors. In rsedu_control.m there is a parameter called onCycles that set the maximum flight time, check that out.

**Comment by drjohnpetersen** [comment]
I couldn't find rsedu_control.m, but I did find rsedu_control.c and changed the parameters there and it worked!  Thankyou.

**Comment by emiliomarin** [comment]
oh yes sorry, I meant .c , good!

**Comment by ChangkiSung** [comment]
How did you figure DroneKeyboardPilot.sh? I have same problem here ( Waiting for Connection to drone)

**Comment by drjohnpetersen** [comment]
You need to run DroneConnect.sh and then DroneKeyboardPilot.sh.  The later needs to be the active terminal so that the keyboard is read in that script.

**Comment by ChangkiSung** [comment]
We are now receiving a 'WARNING not enough distinct color markings.' followed by an error within the leveled surface (which is level). We have also changed the FEAT of Active to 0 so there would no longer be a color marking issue but it has not changed. This is all after a successful DroneTest and DroneRun....no further tests have succeeded.

**Comment by friether** [comment]
Check out the latest major evolution of this toolbox https://www.mathworks.com/hardware-support/parrot-minidrones.html
