### ISSUE TITLE
Unable to get hovering

### ISSUE THREAD

**Issue by emiliomarin** [Parrot-Developers/RollingSpiderEdu#57]
Hi, I've been working with this drone for almost 2 month and I can't get a simple LQR hovering working. Everything looks good but it's not working, I tried changing the parameters in so many ways but still can't get an altitude control. The drone also starts with a constant pitch which I solved by applying an offset during takeoff. 

Anyone has a working project to try it and check if there is a problem with this drone maybe?

Here's an image of the altitude plot.

[http://imgur.com/a/cxOdu](url)
Thank you.

**Comment by mohamedsalem123** [comment]
Hi Emilio, 
I'm having a similar problem and was wondering if you managed to resolve it.

**Comment by emiliomarin** [comment]
@mohamedsalem123 Hi, check if your propellers are damaged, mine were a bit from some crashes and that was the problem. I bought some new and I got hovering again.
