### ISSUE TITLE
Matlab library issues

### ISSUE THREAD

**Issue by allisonwinter123** [Parrot-Developers/RollingSpiderEdu#61]
In the instructions it says to download Matlab 2015. However, there are 3 2015 versions ( a, a SPI, and b). Which one of these is the one you used? I have actually downloaded all of them and they all seem to have the same issue when running the code. They don't have the Gaussian noise generator library (commnoisgen1) which is within the larger Simulink library common sources, and so they are unable to work. Can you please offer some guidance here

**Comment by friether** [comment]
Check out the latest major evolution of this toolbox https://www.mathworks.com/hardware-support/parrot-minidrones.html
