### ISSUE TITLE
LQR fixed pitch during takeoff

### ISSUE THREAD

**Issue by mohamedsalem123** [Parrot-Developers/RollingSpiderEdu#63]
Hello,
I have linearised the model using linearizeDrone_motorcmdTotaste.slx and Simulink's Linear Analysis tool and have added a gain of K_lqr_toMotorcmd to the state_error_datin signal going into the FullstateController block inside the LQR controller block. The drone however does not take off properly and seems to have a constant forward pitch. Does anyone know how I can resolve this issue/if I have done anything wrong?

**Comment by OmarShadeed** [comment]
Hi,
I'm actually facing the same problem. Were you able to fix it ?
Thanks,
